services:
  db:
    image: postgres:16
    container_name: wifimax_odoo_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
    volumes:
      - odoo_db_data:/var/lib/postgresql/data

  odoo:
    image: odoo:18
    container_name: wifimax_odoo
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "8069:8069"
    environment:
      HOST: db
      USER: odoo
      PASSWORD: odoo
    volumes:
      - odoo_web_data:/var/lib/odoo
      - ./custom_addons:/mnt/extra-addons
      - ./config:/etc/odoo

volumes:
  odoo_db_data:
  odoo_web_data: